# Site Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dve" # Custom DVE skin met logo kleuren

locale: "nl-NL"
title: "Drentse Vereniging van Ergotherapeuten"
title_separator: "-"
subtitle: "Samen sterker in de zorg"
name: "DVE"
description: >-
  Samenwerkingsverband van ergotherapeuten in Drenthe. 
  Samen sterker in de zorg voor betere ergotherapeutische ondersteuning.
url: "https://drentseverenigingvanergotherapeuten.netlify.app"
baseurl: ""
repository: "otorenbosch/drentseverenigingvanergotherapeuten"
teaser: # path of fallback teaser image
logo: "/assets/images/dve-logo.png" # Logo toevoegen
masthead_title: # overrides the website title displayed in the masthead

# Site Author
author:
  name: "Drentse Vereniging van Ergotherapeuten"
  avatar: # path of avatar image
  bio: "Wij zijn een netwerk van professionele ergotherapeuten verspreid door heel Drenthe, die samen werken aan de beste zorg voor onze cliënten."
  location: "Drenthe, Nederland"
  email: "info@ergotherapeuten-drenthe.nl"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:info@ergotherapeuten-drenthe.nl"

# Site Footer
footer:

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Europe/Amsterdam

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Collections voor Decap CMS
collections:
  bestuur:
    output: true
    permalink: /:collection/:name/

# Defaults (GEFIXTE VERSIE - slechts één defaults sectie)
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false